- name: Install ssh tools
  package: name={{ item }}
  with_items:
  - xorg
  - xauth
  - openssh-client
  - openssh-server

- name: Add authorized keys
  authorized_key:
    user: "{{ ssh_user_id }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ ssh_pub_files }}"
