- name: Install draw.io dependencies
  become: yes
  package: name={{ item }}
  with_items:
  - libgtk-3-0
  - libnotify4
  - libnss3
  - libxss1
  - libxtst6
  - xdg-utils
  - libatspi2.0-0
  - libuuid1
  - libappindicator3-1
  - libsecret-1-0

- stat:
    path: /usr/bin/drawio
  register: drawio_binary

- name: Install drawio-desktop
  become: yes
  apt:
    deb: https://github.com/jgraph/drawio-desktop/releases/download/v12.3.2/draw.io-amd64-12.3.2.deb
  when: drawio_binary.stat.exists == False
