- name: Install latex tools
  become: yes
  package: name={{ item }}
  with_items:
  - texlive
  - texlive-generic-recommended
  - texlive-pictures
  - texlive-latex-base
  - texlive-latex-recommended
  - texlive-latex-extra
  - texlive-fonts-recommended
  - texlive-fonts-extra
  - texlive-lang-english
  - texlive-lang-german
  - texlive-science
  - texlive-xetex
  - latexmk

- name: Install latex themes
  become: yes
  package: name={{ item }}
  with_items:
  - lmodern

- name: Evaluate latex home
  shell: kpsewhich -var-value=TEXMFHOME
  register: latex_home_output
  changed_when: False

- name: Set latex directory variables
  become: yes
  set_fact:
    latex_home_dir: "{{ latex_home_output.stdout }}"
    latex_package_dir: "{{ latex_home_output.stdout }}/tex/latex/"

- name: Prepare folder for local latex packages
  file:
    path: "{{ latex_package_dir }}"
    state: directory

- name: Install tikz-uml
  unarchive:
    copy: no
    src: "{{ pandoc_tikz_uml_url }}"
    dest: "{{ latex_package_dir }}"
    creates: "{{ latex_package_dir }}/{{ pandoc_tikz_uml_version }}/tikz-uml.sty"

- name: Install pandoc tools
  become: yes
  package: name={{ item }}
  with_items:
  - build-essential
  - make
  - cmake
  - gcc
  - unzip
  - gpp

- name: Install pandoc depedencies
  become: yes
  package: name={{ item }}
  with_items:
  - libc6
  - libgmp10
  - zlib1g

- name: Install pandoc
  become: yes
  apt:
    deb: https://github.com/jgm/pandoc/releases/download/2.8.0.1/pandoc-2.8.0.1-1-amd64.deb

- name: Install FiraSans
  become: yes
  shell: |
    cd /tmp
    mkdir fira
    cd fira
    wget https://github.com/bBoxType/FiraSans/archive/master.zip
    unzip master.zip
    mkdir -p /usr/share/fonts/opentype/fira
    mkdir -p /usr/share/fonts/truetype/fira
    find FiraSans-master/ -name "*.otf" -exec cp {} /usr/share/fonts/opentype/fira/ \;
    find FiraSans-master/ -name "*.ttf" -exec cp {} /usr/share/fonts/truetype/fira/ \;
    cd /tmp
    rm -rf /tmp/fira
  args:
    creates: /usr/share/fonts/opentype/fira/FiraCode-Regular.otf

- name: Install metropolis theme
  become: yes
  shell: |
    cd /tmp
    mkdir metropolis
    cd metropolis
    git clone https://github.com/matze/mtheme.git
    cd mtheme
    git checkout v1.2
    make sty
    make install
    cd /tmp
    rm -rf /tmp/metropolis
  args:
    creates: /usr/share/texlive/texmf-dist/tex/latex/beamertheme-metropolis/beamerthememetropolis.sty

- name: Install markdownlint
  become: yes
  snap:
    name: mdl
