- name: Install build tools
  package: name={{ item }}
  with_items:
  - build-essential
  - gcc
  - cmake
  - automake
  - autoconf
  - pkg-config
  - valgrind
  - gcovr
  - python

- name: Install catch2
  shell: |
    cd /tmp
    mkdir catch
    cd catch
    git clone https://github.com/catchorg/Catch2.git
    cd Catch2
    git checkout v2.6.1
    cmake -Bbuild -H. -DBUILD_TESTING=OFF
    sudo cmake --build build/ --target install
    cd /tmp
    rm -rf /tmp/catch
  args:
    creates: /usr/include/catch2/catch.hpp
