---

- name: add ppa repository
  become: yes
  apt_repository:
    repo: 'ppa:canonical-chromium-builds/stage'
    state: present
    update_cache: yes

- name: install chromium
  become: yes
  apt:
    name: chromium-browser
    state: present
