- name: Install git tools
  package: name={{ item }}
  with_items:
  - git
  - git-gui
  - gitk
  - nano
  - poppler-utils

- name: Set global git settings
  become_user: "{{ git_user_id }}"
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
  - {name: 'user.name', value: '{{ git_user_name }}'}
  - {name: 'user.email', value: '{{ git_user_email }}'}
  - {name: 'push.default', value: 'simple'}
  - {name: 'core.editor ', value: 'nano'}
  - {name: 'alias.pushfwl', value: 'push --force-with-lease'}
  - {name: 'diff.pdf.textconv', value: '/home/{{ git_user_id }}/git-pdftotext.sh'}
  - {name: 'diff.pdf.binary', value: 'true'}

- name: Add git-helper
  become_user: "{{ git_user_id }}"
  copy:
    src: git-helper.bash
    dest: "~/"

- name: Add git-pdftotext
  become_user: "{{ git_user_id }}"
  copy:
    src: git-pdftotext.sh
    dest: "~/"

- name: Make git-pdftotext executable
  become_user: "{{ git_user_id }}"
  file:
    path: "~/git-pdftotext.sh"
    mode: 0755

- name: Ensure Unix line endings
  become_user: "{{ git_user_id }}"
  replace:
    path: "{{ item }}"
    regexp: "\r\n"
    replace: "\n"
  with_items:
  - "~/git-helper.bash"
  - "~/git-pdftotext.sh"

- name: Add git attributes file
  become_user: "{{ git_user_id }}"
  lineinfile:
    dest="~/.config/git/attributes"
    line="{{ item.line }}"
    regexp="{{ item.regexp }}"
    state=present
    insertafter=EOF
    create=True
  with_items:
  - {regexp: "^[*][.]pdf diff=", line: "*.pdf diff=pdf"}

- name: Source git-helper
  become_user: "{{ git_user_id }}"
  blockinfile:
    path: "~/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: git-helper"
    block: |
      if [ -f ~/git-helper.bash ]; then
        source ~/git-helper.bash
        PROMPT_COMMAND="git-find-head-file; $PROMPT_COMMAND"
        export PS1=$GIT_PROMPT
      fi

- name: Source bash completion for git
  become_user: "{{ git_user_id }}"
  blockinfile:
    path: "~/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: bash completion for git"
    block: |
      if [ -f /etc/bash_completion.d/git ]; then
        source /etc/bash_completion.d/git
      fi
