- hosts: all

  pre_tasks:
  - include_tasks: tasks/ubuntu_apt.yml
  - include_tasks: tasks/ubuntu_headless.yml

  tasks:
  - include_tasks: tasks/basicsetup.yml
  - include_tasks: tasks/virtualbox_additions.yml
  - include_tasks: tasks/buildtools.yml

  roles:
  - role: ssh
    vars:
      ssh_pub_files: ['ssh_key_clang_home.opub']

  - role: swapfile
  - role: bash
  - role: tmux
  - role: clion
  - role: hunspell
  - role: google_testing

  - role: fubarhouse.rust
    shell_profiles: ['.bash_profile']

  - role: git-tools
    vars:
      git_aliases: on
      git_rerere: on
      git_editor_nano: on
      git_prompt: on
      git_archivestotext: on
      git_docxtotext: on
      git_pdftotext: on
      git_xlsxtotext: on
      git_user_name: "Christian Lang"
      git_user_email: "lang.chr86@gmail.com"

  - role: dockerce
  - role: pandoc
  - role: drawio
  - role: chromium
  - role: okular
