- hosts: all

  pre_tasks:
  - name: Update package manager repositories
    become: yes
    apt:
      update_cache: yes
    changed_when: False

  - include_tasks: tasks/ubuntu_apt.yml
  - include_tasks: tasks/ubuntu_desktop.yml

  tasks:
  - include_tasks: tasks/basicsetup.yml
  - include_tasks: tasks/virtualbox_additions.yml
  - include_tasks: tasks/buildtools.yml
  - include_tasks: tasks/prcpp.yml

  roles:
  - role: ssh
    vars:
      ssh_pub_files: ['ssh_key_clang_home.opub']

  - role: git-tools
    vars:
      git_user_name: "Christian Lang"
      git_user_email: "christian.lang@fhnw.ch"
      git_rerere: on
      git_editor_nano: on
      git_prompt: on

  - role: swapfile
  - role: bash
  - role: tmux
  - role: clion

  post_tasks:
  - include_tasks: tasks/ubuntu_cleanup.yml

  - name: Shutdown VM
    become: yes
    command: poweroff
