- hosts: all

  pre_tasks:
  - name: Update package manager repositories
    become: yes
    apt:
      update_cache: yes
    changed_when: False

  - include_tasks: tasks/ubuntu_apt.yml
  - include_tasks: tasks/ubuntu_desktop.yml

  tasks:
  - include_tasks: tasks/basicsetup.yml
  - include_tasks: tasks/virtualbox_additions.yml
  - include_tasks: tasks/buildtools.yml
  - include_tasks: tasks/prcpp.yml
  - include_tasks: tasks/okular.yml

  roles:
  - role: ssh
    vars:
      ssh_pub_files: ['ssh_key_clang_home.opub']

  - role: swapfile
  - role: bash
  - role: tmux
  - role: clion
  - role: google_testing

  - role: git-tools
    vars:
      git_aliases: on
      git_rerere: on
      git_editor_nano: on
      git_prompt: on
      git_archivestotext: on
      git_docxtotext: on
      git_pdftotext: on
      git_xlsxtotext: on

  post_tasks:
  - include_tasks: tasks/ubuntu_cleanup.yml

  - name: Shutdown VM
    become: yes
    command: poweroff
