- hosts: all

  pre_tasks:
  - include_tasks: tasks/ubuntu_apt.yml

  - name: Update package manager repositories
    become: yes
    package: update_cache=yes
    changed_when: False

  tasks:
  - include_tasks: tasks/basicsetup.yml
  - include_tasks: tasks/virtualbox_additions.yml
  - include_tasks: tasks/buildtools.yml

  roles:
  - role: ssh
    vars:
      ssh_pub_files: ['ssh_key_clang_home.opub']

  - role: git
    vars:
      git_user_name: "Christian Lang"
      git_user_email: "christian.lang@fhnw.ch"

  - role: swapfile
  - role: bash
  - role: tmux
  - role: clion
  - role: chromium


#  - role: dockerce
#  - role: pandoc
#  - role: drawio
